name: Update Repo Settings

on:
  push:
    branches: [ main ]
    paths: [ .github/settings.yml ]
  pull_request:
    branches: [ main ]
    paths: [ .github/settings.yml ]

jobs:
  apply_settings:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # If this is a PR, dry-run the PR and watch for errors
      - name: Dry-run settings in the PR
        id: dryrun
        continue-on-error: true
        if: github.event_name == 'pull_request'
        uses: elstudio/actions-settings@v3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Explicitly checkout main branch to ensure production settings are reset
      - name: Switch to main for production settings
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: main

      # If this is a PR, dry-run the PR and watch for errors
      - name: Apply production repo settings
        uses: elstudio/actions-settings@v3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
